CREATE TABLE Researchers
(
	RID SMALLINT NOT NULL PRIMARY KEY,
	RFNAme VARCHAR(50) DEFAULT 'TBA',
	RLname VARCHAR(50),
	Gender CHAR(1) CHECK(Gender = 'M' or Gender='F'),
	RTID TINYINT REFERENCES ResearchTeams(REID)
)


ALTER TABLE R_P
ADD CONSTRAINT FK_R_P_Papers
	FOREIGN KEY(PID)
	REFERENCES Papers(PID)
		ON DELETE CASCADE
		ON UPDATE NO ACTION


DROP CONSTRAINT FK_R_P;					


ALTER TABLE R_P
ADD Email VARCHAR(30)

DROP COLUMN RLName

ALTER COLUMN RLName VARCHAR(30)