CREATE DATABASE Lab2
GO
USE Lab2
GO


CREATE TABLE Ingredients
(
	Iid INT PRIMARY KEY IDENTITY,
	Name VARCHAR(50) NOT NULL,
	Quantity INT DEFAULT 0,
	Price FLOAT
) 

CREATE TABLE Tea 
(
	Tid INT PRIMARY KEY,
	Name VARCHAR(50) DEFAULT 'ToBeDefined',
	Quantity INT,
	PRICE FLOAT NOT NULL,
	Iid INT FOREIGN KEY REFERENCES Ingredients(Iid)
)

CREATE TABLE Shops
(
	Sid INT PRIMARY KEY,
	City VARCHAR(50) DEFAULT 'Cluj'
)

CREATE TABLE ShopsTea
(
	Sid INT FOREIGN KEY REFERENCES Shops(Sid),
	Tid INT FOREIGN KEY REFERENCES Tea(Tid),
	CONSTRAINT pk_ShopsTea PRIMARY KEY(Sid, Tid)
)

CREATE TABLE Managers
(
	Mid INT FOREIGN KEY REFERENCES Shops(Sid),
	Name VARCHAR(50),
	Experience DATE,
	CONSTRAINT pk_Managers PRIMARY KEY(Mid)
)